/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    Archive: typeof import('./.vitepress/theme/components/Archive.vue')['default']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ArticleMetadata: typeof import('./.vitepress/theme/components/ArticleMetadata.vue')['default']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    HomeContent: typeof import('./.vitepress/theme/components/HomeContent.vue')['default']
    IntegrationCard: typeof import('./.vitepress/theme/components/IntegrationCard.vue')['default']
    NavHeader: typeof import('./.vitepress/theme/components/NavHeader.vue')['default']
    Tag: typeof import('./.vitepress/theme/components/Tag.vue')['default']
    VPHeroImageLogo: typeof import('./.vitepress/theme/components/VPHeroImageLogo.vue')['default']
    VPHeroImageLogoLayer: typeof import('./.vitepress/theme/components/VPHeroImageLogoLayer.vue')['default']
    WordCloud: typeof import('./.vitepress/theme/components/WordCloud.vue')['default']
  }
}
